services:
  affine:
    image: ghcr.io/timonen87/fineapp:stable

    container_name: affine_selfhosted
    command:
      ['sh', '-c', 'node ./scripts/self-host-predeploy && node ./dist/index.js']
    ports:
      - '3010:3010'
      - '5555:5555'
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      # custom configurations
      - ~/.affine/self-host/config:/root/.affine/config
      # blob storage
      - ~/.affine/self-host/storage:/root/.affine/storage
    logging:
      driver: 'json-file'
      options:
        max-size: '1000m'
    restart: unless-stopped
    environment:
      - NODE_OPTIONS="--import=./scripts/register.js"
      - AFFINE_CONFIG_PATH=/root/.affine/config
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgres://affine:affine@postgres:5432/affine_db_4
      - AFFINE_SERVER_EXTERNAL_URL=http://localhost:3010

      - NODE_ENV=production
      - OAUTH_GOOGLE_CLIENT_ID='54211129985-t7k92hecs8c1bajo0k9eq2vt93jf07p6.apps.googleusercontent.com'
      - OAUTH_GOOGLE_CLIENT_SECRET='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'

      - MAILER_HOST=smtp.gmail.com
      - MAILER_PORT=465
      - MAILER_USER=timonen.as@gmail.com
      - MAILER_PASSWORD=dmjlguvuqxunggfr
      - MAILER_SENDER=timonen.as@gmail.com
      - MAILER_SECURE=true

      - R2_ACCESS_KEY_ID=g9qBxGAaJkPWLHwnGGb1sP
      - R2_SECRET_ACCESS_KEY=Hn1VTjmwGAhMpWBhW5YFSGjnGsQUgwQnirUJ1p4LBRL
      - REGIONAL_VK_S3_ACCOUNT=ru-msk

      # AWS_SECRET_ACCESS_KEY=39QT3CMSFKwSivprv9uK37NtGM7rQyb4vMpckhDZQ5Wk
      # AWS_S3_ENDPOINT_URL=https://wiki-bucket.hb.ru-msk.vkcs.cloud
      # AWS_ACCESS_KEY_ID=t1JiJU4oHoPJBMBQZFcWCD
      # - AWS_S3_USE_SSL=false
      # - AWS_ACCESS_KEY_ID=i8s2Uwq1JKPcDuyxXtRv5S
      # - AWS_SECRET_ACCESS_KEY=cCxbofnCBXzXFe4yg4XgZCW3HRyZFQTSyfBfty4LVojq
      # - AWS_S3_ENDPOINT_URL=https://wiki-bucket.hb.ru-msk.vkcs.cloud
      # - AWS_S3_REGION_NAME=ru-msk

      # - AFFINE_ADMIN_EMAIL=${AFFINE_ADMIN_EMAIL}
      # - AFFINE_ADMIN_PASSWORD=${AFFINE_ADMIN_PASSWORD}
      - AFFINE_ADMIN_EMAIL=timonen.as@gmail.com
      - AFFINE_ADMIN_PASSWORD=13Tarantul
      # Telemetry allows us to collect data on how you use the affine. This data will helps us improve the app and provide better features.
      # Uncomment next line if you wish to quit telemetry.
      # - TELEMETRY_ENABLE=false
  redis:
    image: redis
    container_name: affine_redis
    restart: unless-stopped
    volumes:
      - ~/.affine/self-host/redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres
    container_name: affine_postgres
    restart: unless-stopped
    volumes:
      - ~/.affine/self-host/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U affine']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: affine
      POSTGRES_PASSWORD: affine
      POSTGRES_DB: affine
      PGDATA: /var/lib/postgresql/data/pgdata
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    container_name: watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=1800
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
